# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

name: Run the test suite

on:
  pull_request:
  push:
  schedule:
    - cron: '0 14 * * 5'  # Every Friday 2pm
  workflow_dispatch:

# Drop permissions to minimum for security
permissions:
  contents: read

jobs:
  run-tests:
    name: Run the test suite (${{ matrix.gcc }}, ${{ matrix.runs-on }}, Python ${{ matrix.gcc }})
    strategy:
      fail-fast: false
      matrix:
        include:
            # No particular need for in-between versions of Python
          - gcc: gcc-7
            install: gcc-7
            python-version: 3.9
            runs-on: ubuntu-20.04
          - gcc: gcc-12
            install: null
            python-version: 3.9
            runs-on: macos-13
          - gcc: gcc-12
            install: null
            python-version: 3.12
            runs-on: macos-13
          - gcc: gcc-12
            install: null
            python-version: 3.9
            runs-on: ubuntu-22.04
          - gcc: gcc-12
            install: null
            python-version: 3.12
            runs-on: ubuntu-22.04
          - gcc: gcc-14
            install: null
            python-version: 3.12
            runs-on: ubuntu-24.04
          - gcc: gcc-15
            install: binutils gcc-15
            python-version: 3.12
            runs-on: ubuntu-24.04
          - gcc: musl-gcc
            install: musl-tools
            python-version: 3.12
            runs-on: ubuntu-24.04
    runs-on: ${{ matrix.runs-on }}
    steps:

    - name: Add GCC 15 Ubuntu repositories
      if: "${{ matrix.gcc == 'gcc-15' }}"
      run: |
           set -x
           # The repository is at home at https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test .
           # NOTE: plucky is 25.04 (not 24.04 LTS)
           wget -O - 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc8ec952e2a0e1fbdc5090f6a2c277a0a352154e5' | sudo apt-key add -
           sudo add-apt-repository 'deb https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu plucky main'
           sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ plucky main'

    - name: Install runtime dependencies
      if: "${{ matrix.install }}"
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes -V ${{ matrix.install }}

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run the test suite
      run: |
        set -x
        python3 --version
        pip3 install -U setuptools  # for Python >=3.12
        pip3 install --require-hashes -r requirements.txt
        pytest -v -s -Wdefault -Werror

    - name: Smoke test the CLI
      env:
        gcc: ${{ matrix.gcc }}
      run: |
        set -x
        pip3 install -e .
        resolve-march-native --gcc="${gcc}" --vertical
