# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

name: Run the test suite

on:
  pull_request:
  push:
  schedule:
    - cron: '0 14 * * 5'  # Every Friday 2pm
  workflow_dispatch:

# Drop permissions to minimum for security
permissions:
  contents: read

jobs:
  run-tests:
    name: Run the test suite
    strategy:
      matrix:
        include:
            # No particular need for in-between versions of Python
          - python-version: 3.9
            runs-on: macos-13
          - python-version: 3.12
            runs-on: macos-13
          - python-version: 3.9
            runs-on: ubuntu-22.04
          - python-version: 3.12
            runs-on: ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run the test suite
      run: |
        set -x
        python3 --version
        pip3 install -U setuptools  # for Python >=3.12
        pip3 install --require-hashes -r requirements.txt
        pytest -v -s -Wdefault -Werror

    - name: Smoke test the CLI
      run: |
        set -x
        pip3 install -e .
        resolve-march-native --gcc=gcc-12 --vertical
