# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

name: Run the test suite

on:
- pull_request
- push

jobs:
  run-tests:
    name: Run the test suite
    strategy:
      matrix:
        python-version: [3.9, 3.12]  # no particular need for in-between versions
        runs-on: [macos-13, ubuntu-22.04]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run the test suite
      run: |
        set -x
        python3 --version
        pip3 install -U setuptools  # for Python >=3.12
        pip3 install --require-hashes -r requirements.txt
        pytest -v -s -Wdefault -Werror

    - name: Smoke test the CLI
      run: |
        set -x
        pip3 install -e .
        resolve-march-native --gcc=gcc-12 --vertical
